dependencies:
- name: dspl-download-csv
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
- name: dspl-frontend-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.136
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
